### ISSUE TITLE
Missing UnityEngine.InputSystem.Switch while building to Linux

### ISSUE THREAD

**Issue by TheMatiaz0** [eviltwo/InputGlyphs#75]
```csharp
namespace UnityEngine.InputSystem.Switch
{
#if UNITY_EDITOR || UNITY_STANDALONE_WIN || UNITY_STANDALONE_OSX || UNITY_WSA || PACKAGE_DOCS_GENERATION
    /// <summary>
    /// A Nintendo Switch Pro controller connected to a desktop mac/windows PC using the HID interface.
    /// </summary>
    [InputControlLayout(stateType = typeof(SwitchProControllerHIDInputState), displayName = "Switch Pro Controller")]
    public class SwitchProControllerHID : Gamepad, IInputStateCallbackReceiver, IEventPreProcessor
```
It seems that unfortunately Unity doesn't implement SwitchProControllerHID for UNITY_STANDALONE_LINUX (and all other platforms aside from Windows and MacOS) causing it to fail during build process.

### How to reproduce?
1. Enter Build Settings,
2. Pick Target Platform to Linux (remember to install any Linux module from Unity Hub),
3. Press Build button.

### Result
`Library/PackageCache/com.eviltwo.input-glyphs@992d53a834/Scripts/Runtime/Loaders/Gamepad/GamepadGlyphLoader.cs(9,31): error CS0234: The type or namespace name 'Switch' does not exist in the namespace 'UnityEngine.InputSystem' (are you missing an assembly reference?)`

`Library/PackageCache/com.eviltwo.unity-steam-input-adapter@9d9b8060e5/Scripts/SteamInputAdapter.cs(7,31): error CS0234: The type or namespace name 'Switch' does not exist in the namespace 'UnityEngine.InputSystem' (are you missing an assembly reference?)`

As you can see from the logs the issue fires from InputGlyphs and UnitySteamInputAdapter packages.

**Comment by eviltwo** [comment]
I didn't realize there were errors in the Linux build. Thank you for fixing them! I truly appreciate your contribution.

**Comment by eviltwo** [comment]
It seems that the same error occurs with the DualSense as well.  
I will fix it in the same way as with the Switch.
```
Library\PackageCache\com.eviltwo.unity-steam-input-adapter\Scripts\SteamInputAdapter.cs(123,22): error CS0103: The name 'DualSenseGamepadHID' does not exist in the current context
```

**Comment by TheMatiaz0** [comment]
Oh, you are definitely right! Just had the same error. Sorry for not testing the issue properly earlier. Damn it Unity :P
I left build machine running in the background cause of late hours, I thought that Switch was the only culprit.

**Comment by eviltwo** [comment]
In the Windows build, we want to enable recognition of Switch Pro and PS5 controllers, so I plan to use `#if UNITY_EDITOR || UNITY_STANDALONE_WIN || UNITY_STANDALONE_OSX || UNITY_WSA` instead of `#if UNITY_SWITCH` or `#if UNITY_PS5`.

**Comment by eviltwo** [comment]
TODO
- [ ] UnitySteamInputAdapter
- [ ] InputGlyphs

**Comment by eviltwo** [comment]
Done!
